materials:
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - EMERALD_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - DIAMOND_ORE

  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_DIAMOND_ORE

  - ANCIENT_DEBRIS
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE

  - ACACIA_LOG
  - BIRCH_LOG
  - DARK_OAK_LOG
  - JUNGLE_LOG
  - OAK_LOG
  - SPRUCE_LOG
  - CRIMSON_STEM
  - WARPED_STEM
