main: me.trqhxrd.veinminer.Main
version: ${project.version}
api-version: 1.18

name: VeinMiner
author: Trqhxrd
website: https://github.com/Trqhxrd/VeinMiner

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21
