name: Java Test for Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
          server-id: trqhxrd
          server-username: M2_USERNAME
          server-password: M2_PASSWORD
      - name: Test with Maven
        run: ./mvnw -B clean test
      - name: Package with Maven
        run: ./mvnw -B clean package
